name: Create Plugin Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Plugin Zip
        run: ./scripts/package.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
