name: Create Plugin Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Plugin Zip
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          mkdir -p "dist/$REPO_NAME.koreader"
          rsync -av --exclude='.git*' --exclude='.github' --exclude='dist' --exclude='koreader' --exclude='.luarc.json' --exclude='GEMINI.md' ./ "dist/$REPO_NAME.koreader/"
          cd dist && zip -r "../$REPO_NAME.zip" "$REPO_NAME.koreader"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"